spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}?currentSchema=saludo
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    password: ${DB_PASSWORD}
    schemas: saludo
    user: ${DB_USER}