---
name: Create Github Issue
description: Creates a new github issue as directly as possible
author: Daniel Barnes
branding:
  icon: alert-octagon
  color: gray-dark
runs:
  using: node16
  main: ./dist/index.js
inputs:
  token:
    description: Your Github PAT, defaults to actions token
    required: false
  owner:
    description: Repo Owner, if not set implied by context.
    required: false
  repo:
    description: Repo or impiled by the current context
    required: false
  title:
    description: Issue title
    required: true
  body:
    description: Body content of issue
    required: false
  milestone: 
    description: Milestone associated with issue
    required: false
  labels:
    description: CSV of labels (e.x. 'p0-critial,bug,aws')
    required: false
  assignees:
    description: CSV of github usernames to assign (e.x. 'dacbd,nlf')
    required: false
outputs:
  json:
    description: The JSON for the new created issue returned from the GitHub API
  html_url:
    description: The web url of the new issue
  number:
    description: "The new issue's number"